import React from 'react';

interface CountryFlagProps {
  countryName: string;
  countryCode?: string;
  className?: string;
}

const CountryFlag: React.FC<CountryFlagProps> = ({ countryName, countryCode, className = "" }) => {
  // Map of country names to flag emojis
  const countryFlags: Record<string, string> = {
    'Nigeria': '🇳🇬',
    'USA': '🇺🇸',
    'Canada': '🇨🇦',
    'United Kingdom': '🇬🇧',
    'France': '🇫🇷',
    'Germany': '🇩🇪',
    'Italy': '🇮🇹',
    'Spain': '🇪🇸',
    'Netherlands': '🇳🇱',
    'Switzerland': '🇨🇭',
    'Sweden': '🇸🇪',
    'Norway': '🇳🇴',
    'Denmark': '🇩🇰',
    'Finland': '🇫🇮',
    'Portugal': '🇵🇹',
    'Greece': '🇬🇷',
    'Turkey': '🇹🇷',
    'Egypt': '🇪🇬',
    'South Africa': '🇿🇦',
    'Kenya': '🇰🇪',
    'Uganda': '🇺🇬',
    'Ghana': '🇬🇭',
    'Ivory Coast': '🇨🇮',
    'Benin': '🇧🇯',
    'Togo': '🇹🇬',
    'Niger': '🇳🇪',
    'Algeria': '🇩🇿',
    'Morocco': '🇲🇦',
    'Tunisia': '🇹🇳',
    'Libya': '🇱🇾',
    'Ethiopia': '🇪🇹',
    'Mozambique': '🇲🇿',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
    'Malawi': '🇲🇼',
    'Lesotho': '🇱🇸',
    'Botswana': '🇧🇼',
    'Eswatini': '🇸🇿',
    'Comoros': '🇰🇲',
    'Rwanda': '🇷🇼',
    'Burundi': '🇧🇮',
    'Equatorial Guinea': '🇬🇶',
    'Gabon': '🇬🇦',
    'Congo (Brazzaville)': '🇨🇬',
    'Congo (Kinshasa)': '🇨🇩',
    'Angola': '🇦🇴',
    'Guinea-Bissau': '🇬🇼',
    'Seychelles': '🇸🇨',
    'Tanzania': '🇹🇿',
    'Gambia': '🇬🇲',
    'Senegal': '🇸🇳',
    'Mauritania': '🇲🇷',
    'Mali': '🇲🇱',
    'Guinea': '🇬🇳',
    'Burkina Faso': '🇧🇫',
    'Sierra Leone': '🇸🇱',
    'Liberia': '🇱🇷',
    'Cameroon': '🇨🇲',
    'Cape Verde': '🇨🇻',
    'Sao Tome & Principe': '🇸🇹',
    'Mauritius': '🇲🇺',
    'Madagascar': '🇲🇬',
    'Reunion': '🇷🇪',
    'Mayotte': '🇾🇹',
    'Saint Helena': '🇸🇭',
    'Eritrea': '🇪🇷',
    'Aruba': '🇦🇼',
    'Bonaire, Sint Eustatius & Saba': '🇧🇶',
    'Greenland': '🇬🇱',
    'Luxembourg': '🇱🇺',
    'Ireland': '🇮🇪',
    'Iceland': '🇮🇸',
    'Albania': '🇦🇱',
    'Malta': '🇲🇹',
    'Cyprus': '🇨🇾',
    'Bulgaria': '🇧🇬',
    'Hungary': '🇭🇺',
    'Lithuania': '🇱🇹',
    'Latvia': '🇱🇻',
    'Estonia': '🇪🇪',
    'Moldova': '🇲🇩',
    'Armenia': '🇦🇲',
    'Belarus': '🇧🇾',
    'Andorra': '🇦🇩',
    'Monaco': '🇲🇨',
    'San Marino': '🇸🇲',
    'Ukraine': '🇺🇦',
    'Serbia': '🇷🇸',
    'Montenegro': '🇲🇪',
    'Kosovo': '🇽🇰',
    'Croatia': '🇭🇷',
    'Slovenia': '🇸🇮',
    'Bosnia & Herzegovina': '🇧🇦',
    'North Macedonia': '🇲🇰',
    'Romania': '🇷🇴',
    'Austria': '🇦🇹',
    'Czech Republic': '🇨🇿',
    'Slovakia': '🇸🇰',
    'Liechtenstein': '🇱🇮',
    'Russia/Kazakhstan': '🇷🇺',
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'Vietnam': '🇻🇳',
    'China': '🇨🇳',
    'Hong Kong': '🇭🇰',
    'Macau': '🇲🇴',
    'Cambodia': '🇰🇭',
    'Laos': '🇱🇦',
    'Malaysia': '🇲🇾',
    'Australia': '🇦🇺',
    'Indonesia': '🇮🇩',
    'Philippines': '🇵🇭',
    'New Zealand': '🇳🇿',
    'Singapore': '🇸🇬',
    'Thailand': '🇹🇭',
    'East Timor': '🇹🇱',
    'Australian External Territories': '🇦🇺',
    'Brunei': '🇧🇳',
    'Nauru': '🇳🇷',
    'Papua New Guinea': '🇵🇬',
    'Tonga': '🇹🇴',
    'Solomon Islands': '🇸🇧',
    'Vanuatu': '🇻🇺',
    'Fiji': '🇫🇯',
    'Palau': '🇵🇼',
    'Wallis & Futuna': '🇼🇫',
    'Cook Islands': '🇨🇰',
    'Niue': '🇳🇺',
    'American Samoa': '🇦🇸',
    'Samoa': '🇼🇸',
    'Kiribati': '🇰🇮',
    'New Caledonia': '🇳🇨',
    'Tuvalu': '🇹🇻',
    'French Polynesia': '🇵🇫',
    'Tokelau': '🇹🇰',
    'Micronesia': '🇫🇲',
    'Marshall Islands': '🇲🇭',
    'North Korea': '🇰🇵',
    'Bangladesh': '🇧🇩',
    'Global Mobile Satellite System': '🛰️',
    'International Networks': '🌐',
    'Taiwan': '🇹🇼',
    'Maldives': '🇲🇻',
    'Lebanon': '🇱🇧',
    'Jordan': '🇯🇴',
    'Syria': '🇸🇾',
    'Iraq': '🇮🇶',
    'Kuwait': '🇰🇼',
    'Saudi Arabia': '🇸🇦',
    'Yemen': '🇾🇪',
    'Oman': '🇴🇲',
    'Palestine': '🇵🇸',
    'United Arab Emirates': '🇦🇪',
    'Israel': '🇮🇱',
    'Bahrain': '🇧🇭',
    'Qatar': '🇶🇦',
    'Bhutan': '🇧🇹',
    'Mongolia': '🇲🇳',
    'Nepal': '🇳🇵',
    'Pakistan': '🇵🇰',
    'Afghanistan': '🇦🇫',
    'Sri Lanka': '🇱🇰',
    'Myanmar': '🇲🇲',
    'Iran': '🇮🇷',
    'Azerbaijan': '🇦🇿',
    'Georgia': '🇬🇪',
    'Kyrgyzstan': '🇰🇬',
    'Uzbekistan': '🇺🇿',
    'Tajikistan': '🇹🇯',
    'Turkmenistan': '🇹🇲',
    'Bahamas': '🇧🇸',
    'Barbados': '🇧🇧',
    'Anguilla': '🇦🇮',
    'Antigua & Barbuda': '🇦🇬',
    'British Virgin Islands': '🇻🇬',
    'US Virgin Islands': '🇻🇮',
    'Cayman Islands': '🇰🇾',
    'Bermuda': '🇧🇲',
    'Grenada': '🇬🇩',
    'Turks & Caicos Islands': '🇹🇨',
    'Montserrat': '🇲🇸',
    'Northern Mariana Islands': '🇲🇵',
    'Guam': '🇬🇺',
    'Sint Maarten': '🇸🇽',
    'St. Lucia': '🇱🇨',
    'Dominica': '🇩🇲',
    'St. Vincent & Grenadines': '🇻🇨',
    'Puerto Rico': '🇵🇷',
    'Dominican Republic': '🇩🇴',
    'Trinidad & Tobago': '🇹🇹',
    'St. Kitts & Nevis': '🇰🇳',
    'Jamaica': '🇯🇲',
  };

  const getFlag = (name: string): string => {
    return countryFlags[name] || '🌍';
  };

  const flag = getFlag(countryName);

  return (
    <span className={`text-2xl ${className}`} title={countryName}>
      {flag}
    </span>
  );
};

export default CountryFlag;
